const namesData = 
[
    { sr: "1", name: "Pohe", quantity: 0, price: 20, cost: 0 },
    { sr: "2", name: "Upma", quantity: 0, price: 20, cost: 0 },
    { sr: "3", name: "Meduwada Sambar", quantity: 0, price: 30, cost: 0 },
    { sr: "4", name: "Idli Sambar", quantity: 0, price: 30, cost: 0 },
    { sr: "5", name: "Batata Wada Sambar", quantity: 0, price: 30, cost: 0 },
    { sr: "6", name: "Single Idli Sambar", quantity: 0, price: 20, cost: 0 },
    { sr: "7", name: "Single Meduwada Sambar", quantity: 0, price: 20, cost: 0 },
    { sr: "8", name: "Single Batata Wada Sambar", quantity: 0, price: 20, cost: 0 },
    { sr: "9", name: "Bread Patis", quantity: 0, price: 15, cost: 0 },
    { sr: "10", name: "Samosa", quantity: 0, price: 15, cost: 0 },
    { sr: "11", name: "Wada Pav", quantity: 0, price: 15, cost: 0 },
    { sr: "12", name: "Maggi", quantity: 0, price: 20, cost: 0 },
    { sr: "13", name: "Veg Maggi", quantity: 0, price: 30, cost: 0 },
    { sr: "14", name: "Cheese Maggi", quantity: 0, price: 35, cost: 0 },
    { sr: "15", name: "Veg Cheese Maggi", quantity: 0, price: 45, cost: 0 },
    { sr: "16", name: "Cream Roll/ BreadRoll", quantity: 0, price: 10, cost: 0 },
    { sr: "17", name: "Poli Bhaji", quantity: 0, price: 40, cost: 0 },
    { sr: "18", name: "Dal Rice", quantity: 0, price: 40, cost: 0 },
    { sr: "19", name: "Butter Milk", quantity: 0, price: 20, cost: 0 },
    { sr: "20", name: "Poli", quantity: 0, price: 6, cost: 0 },
    { sr: "21", name: "Bhaji Plate / Rice / Dal Plate", quantity: 0, price: 20, cost: 0 },
    { sr: "22", name: "Limbu Sarbat", quantity: 0, price: 10, cost: 0 },
    { sr: "23", name: "Thali", quantity: 0, price: 70, cost: 0 },
    { sr: "24", name: "Dahi", quantity: 0, price: 10, cost: 0 },
    { sr: "25", name: "Mango / Aam Panha / Guava Drink", quantity: 0, price: 20, cost: 0 },
    { sr: "26", name: "Lassi", quantity: 0, price: 30, cost: 0 },
    { sr: "27", name: "Flavour Milk", quantity: 0, price: 30, cost: 0 },
    { sr: "28", name: "Mazha / Apple Drink 150ml", quantity: 0, price: 10, cost: 0 },
    { sr: "29", name: "Cold Drinks", quantity: 0, price: 20, cost: 0 },
    { sr: "30", name: "Minutemiad Juices", quantity: 0, price: 20, cost: 0 },
    { sr: "31", name: "Water 500ml", quantity: 0, price: 10, cost: 0 },
    { sr: "32", name: "Water 1L Bottle", quantity: 0, price: 20, cost: 0 },
    { sr: "33", name: "Shrikhand", quantity: 0, price: 30, cost: 0 },
    { sr: "34", name: "Mazha 250ml", quantity: 0, price: 20, cost: 0 },
    { sr: "35", name: "Nestle Cold Coffee", quantity: 0, price: 40, cost: 0 },
    { sr: "36", name: "Nestle Mylo Drink", quantity: 0, price: 40, cost: 0 },
    { sr: "37", name: "Nestle Ice Tea", quantity: 0, price: 30, cost: 0 },
    { sr: "38", name: "Munch", quantity: 0, price: 5, cost: 0 },
    { sr: "39", name: "Kitkat", quantity: 0, price: 10, cost: 0 },
    { sr: "40", name: "Sweet Dish", quantity: 0, price: 20, cost: 0 },
    { sr: "41", name: "Tea", quantity: 0, price: 10, cost: 0 },
    { sr: "42", name: "Coffee", quantity: 0, price: 20, cost: 0 },
    { sr: "43", name: "Bournvita", quantity: 0, price: 25, cost: 0 },
    { sr: "44", name: "Plain Milk / Haldi Milk", quantity: 0, price: 20, cost: 0 },
    { sr: "45", name: "Paneer Sabji", quantity: 0, price: 35, cost: 0 },
]

export default namesData;